### ISSUE TITLE
Cannot use toggle at first

### ISSUE THREAD

**Issue by arthurcgusmao** [jeffgran/atom-selection-mode#1]
Hey, thanks for the great work so far.

The issue I'm having is the following: at first, the command "selection-mode:toggle" is not available (and when I press the keybinding associated with it it does nothing). I can only use "selection-mode:toggle-without-deselecting" at first, and once this command has been used "selection-mode:toggle" becomes available.

I don't know if this was the intended behavior. Thanks for all the support.

**Comment by jeffgran** [comment]
weird. I'm not sure what would cause that. I know it was working right a couple years ago when I first wrote it. :) I am not using Atom any more (went back to emacs), so I probably won't spend any time looking into this, but very open to pull requests if you figure out what is causing that. Seems like it would be a performance optimization they made in loading plugins... maybe you have to specify which commands are "eager loaded" or something?
