### ISSUE TITLE
Cannot update from version 0.2.1 on Linux

### ISSUE THREAD

**Issue by sdturne** [jeffgran/atom-selection-mode#5]
The update fails because the "latest version" reported at:
https://atom.io/packages/selection-mode
claims 0.4.0 and this version does not exist.
Atom fails the update with a 404 error:

Updating to “selection-mode@0.4.0” failed.Hide output…
/bin/bash: module: line 1: syntax error: unexpected end of file
/bin/bash: error importing function definition for `BASH_FUNC_module'

Unable to download https://www.atom.io/api/packages/selection-mode/versions/0.4.0/tarball: 404

**Comment by jeffgran** [comment]
weird, that must have happened somehow when I was fighting with publishing 0.3.0.

Tell you what, I'll just re-publish 0.3.0 as 0.4.0 again so that it exists.

**Comment by jeffgran** [comment]
@sdturne can you try now? Does it work? Sorry for the delayed response.

**Comment by sdturne** [comment]
Yes its does, thank you.  Closing this issue.
